export const ORGANIZATIONS = [
  "Tuman hokimining birinchi o‘rinbosari",
  "Tuman hokimining o‘rinbosari",
  "Mahalla uyushmasi",
  "Bandlik bo‘limi",
  "Soliq inspeksiyasi",
  "Xalq ta'limi",
  "Qishloq xo‘jaligi bo'limi",
  "IJQK Departamenti (Iqtisodiy jinoyatlarga qarshi kurashish departamenti)",
  "Fermerlar kengashi",
  "Kadastr palatasi",
  "Kadastr agentligi",
  "Irrigatsiya bo'limi",
  "Ekologiya bo‘limi",
  "Agroinspeksiya",
  "Veterinariya bo‘limi",
  "Elektr tarmoqlari korxonasi",
  "Gaz ta'minoti bo'limi",
  "Qurilish bo‘limi",
  "Jomboy tibbiyot birlashmasi",
  "Tuman IIB - DAN (Yo'l harakati xavfsizligi)",
  "Tuman MIB (Majburiy ijro byurosi)",
  "Tuman statistika bo'limi"
];
