export const ORGANIZATIONS = [
  "Tuman hokimining birinchi o’rinbosari",
  "Tuman hokimining qurilish bo’yicha o’rinbosari",
  "Tuman hokimining qishloq xo’jaligi bo’yicha o’rinbosari",
  "Soliq inspeksiyasi",
  "IJQK Departamenti",
  "Tuman MIB",
  "Qishloq xo’jaligi bo’limi",
  "Mahalla uyushmasi",
  "Bandlik bo’limi",
  "Xalq ta’limi bo’limi",
  "Fermerlar kengashi",
  "Kadastr palatasi",
  "Irrigatsiya bo’limi",
  "Ekologiya bo’limi",
  "Agroinspeksiya",
  "Veterinariya bo’limi",
  "Elektr tarmoqlari",
  "Gaz ta’minoti",
  "Qurilish bo’limi",
  "Kadastr agentligi",
  "Jomboy tibbiyot birlashmasi",
  "Tuman IIB",
  "Tuman statistika bo’limi"
];
